--1
--학생이름과 주소지를 표시하시오. 단, 출력 헤더는 "학생 이름", "주소지"로 하고,
--정렬은 이름으로 오름차순 표시하도록 한다.

SELECT STUDENT_NAME 학생이름, STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY 학생이름;

--2
SELECT STUDENT_NAME, STUDENT_SSN 
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY SUBSTR(STUDENT_SSN, 1, 6) DESC; 

--3
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS AS "거주지 주소"
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO, 1) = 9 AND SUBSTR(STUDENT_ADDRESS, 1, 3) = '경기도'
ORDER BY STUDENT_NAME;

--4
SELECT PROFESSOR_NAME, PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = 005
ORDER BY SUBSTR(PROFESSOR_SSN, 1, 6); 

--5
SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE CLASS_NO = 'C3118100' AND TERM_NO = 200402
ORDER BY POINT DESC ;

--6
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME  
FROM TB_STUDENT, TB_DEPARTMENT
ORDER BY STUDENT_NAME DESC

